version: "3"
services:
  app:
    container_name: sqs_idempotency
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./sqs_idempotency:/app
    working_dir: /app
    tty: true
